### ISSUE TITLE
SyntaxError: The requested module 'yargs' does not provide an export named 'argv'

### ISSUE THREAD

**Issue by gokhangunduz** [adamreisnz/replace-in-file#195] opened 2024-06-24 12:56 UTC
Hi, i have a problem, can you help me? the error following when i upgraded to 8.0.0 version of replace-in-file library.

```bash
Compiling...
file:///C:/Users/user/react-project/node_modules/replace-in-file/bin/cli.js:3
import {argv} from 'yargs'
        ^^^^
SyntaxError: The requested module 'yargs' does not provide an export named 'argv'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.14.0
ERROR: "cleanWarning" exited with 1.
```

- React: v18.3.1
- Node: v20.14.0

like issue: https://github.com/adamreisnz/replace-in-file/issues/194

**Comment by AryanJ-NYC** [comment] 2024-06-25 00:58
> Hi, i have a problem, can you help me? the error following when i upgraded to 8.0.0 version of replace-in-file library.
> 
> ```shell
> Compiling...
> file:///C:/Users/user/react-project/node_modules/replace-in-file/bin/cli.js:3
> import {argv} from 'yargs'
>         ^^^^
> SyntaxError: The requested module 'yargs' does not provide an export named 'argv'
>     at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
>     at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
>     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
>     at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
> 
> Node.js v20.14.0
> ERROR: "cleanWarning" exited with 1.
> ```
> 
> * React: v18.3.1
> * Node: v20.14.0
> 
> like issue: #194

If you saw an existing issue for your _exact_ problem, why create a new issue?

**Comment by adamreisnz** [comment] 2024-06-25 04:35
Duplicate of #194

**Closed by adamreisnz** 2024-06-25 04:34 UTC
