### ISSUE TITLE
Replace in hidden files in MacOS not working?

### ISSUE THREAD

**Issue by Ronald-Diemicke** [adamreisnz/replace-in-file#103] opened 2020-01-02 16:34 UTC
I'm trying to do a replace in hidden files (starting with a '.') but it's not working. Any ideas?

**Comment by adamreisnz** [comment] 2020-01-02 23:15
Do you mean they aren't being found? Probably need to work on your regex for file matching.

**Comment by adamreisnz** [comment] 2020-02-03 19:56
Closing this one off now, but let me know if you still run into issues.

**Closed by adamreisnz** 2020-02-03 19:56 UTC

**Comment by butaca** [comment] 2024-08-04 20:43
I'm experience the same issue on macOS

**Comment by butaca** [comment] 2024-08-04 20:49
The problem is that by default glob is ignoring paths starting with dots. This can be changed with this configuration: https://www.npmjs.com/package/replace-in-file#specify-glob-configuration

```
const options = {
  glob: {
    dot: true,
  },
}
```
